# on:
#   schedule:
#     - cron: '0 20,8 * * *'

on:
  push:
    branches:
      - main

jobs:
  status:
    name: Status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - run: npm test
        continue-on-error: true
      - name: create env file
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
      - run: npm run discord